### ISSUE TITLE
java.lang.UnsupportedOperationException: Method setTransactionIsolation in class org.neo4j.jdbc.Connection is not yet implemented.

### ISSUE THREAD

**Issue by jaxzin** [neo4j/neo4j-jdbc#68] opened 2016-07-21 01:44 UTC
This is in the 3.0 release of the `neo4j-jdbc-bolt` and `neo4j-jdbc-http` drivers. In my case I'm using [sql2o](http://www.sql2o.org/) but I suspect anyone using transactions via an ORM or Spring JdbcTemplate will run into this same issue.

```
! java.lang.UnsupportedOperationException: Method setTransactionIsolation in class org.neo4j.jdbc.Connection is not yet implemented.
! at org.neo4j.jdbc.utils.ExceptionBuilder.buildUnsupportedOperationException(ExceptionBuilder.java:41) ~[neo4j-jdbc-http-3.0.jar:na]
! at org.neo4j.jdbc.Connection.setTransactionIsolation(Connection.java:308) ~[neo4j-jdbc-http-3.0.jar:na]
! at org.sql2o.Sql2o.beginTransaction(Sql2o.java:344) ~[sql2o-1.5.1.jar:na]
! at org.sql2o.Sql2o.beginTransaction(Sql2o.java:359) ~[sql2o-1.5.1.jar:na]
```

**Comment by inserpio** [comment] 2016-07-21 12:54
Hi @jaxzin, thanks for your feedback. We're going to release a patch for this asap. Stay tuned.

**Comment by inserpio** [comment] 2016-07-21 17:11
This should be fixed for both BOLT and HTTP modules with 62fbaa1

A new snapshot version jar is available here: https://github.com/neo4j-contrib/neo4j-jdbc/releases/download/3.0.1-SNAPSHOT/neo4j-jdbc-driver-3.0.1-SNAPSHOT.jar

Can you please try it out and give us a feedback?

Thank you

**Comment by jaxzin** [comment] 2016-07-21 18:05
@inserpio Is there a Maven snapshot repo I can point to?

**Comment by inserpio** [comment] 2016-07-21 18:23
@jaxzin generically speaking yes (https://m2.neo4j.org/content/repositories/snapshots/) but we haven't published the 3.0.1 snapshot yet, sorry.

In the meantime, could you please download it (from the above link) and add it to your local maven repo via the classic:

```
mvn install:install-file -Dfile=neo4j-jdbc-driver-3.0.1-SNAPSHOT.jar -DgroupId=org.neo4j -DartifactId=neo4j-jdbc -Dversion=3.0.1-SNAPSHOT -Dpackaging=jar
```

**Comment by inserpio** [comment] 2016-07-21 18:29
In the meantime I've just created a small test class like this and it looks like this work fine:

```
public class Sql2oTest {

    @Test
    public void shouldExecuteStatementViaSql2oAndBolt() {

        Sql2o sql2o = new Sql2o("jdbc:neo4j:bolt://localhost?noSsl", "neo4j", "larusba");

        String sql = "match (n) where \"Movie\" in labels(n) return n.title limit 1";

        try (Connection con = sql2o.open()) {
            System.out.println(con.createQuery(sql).executeScalar());
        }
    }

    @Test
    public void shouldExecuteHttpStatementViaSql2oAndHTTP() {

        Sql2o sql2o = new Sql2o("jdbc:neo4j:http://localhost?noSsl", "neo4j", "larusba");

        String sql = "match (n) where \"Movie\" in labels(n) return n.title limit 1";

        try (Connection con = sql2o.open()) {
            System.out.println(con.createQuery(sql).executeScalar());
        }
    }
}
```

BTW. How do you manage labels with Sql2o? I notice it understands `:Movie` as a parameter!?

**Comment by jaxzin** [comment] 2016-07-21 21:00
Thanks for the fast turnaround. I get further but it looks like we'll be playing whack-a-mole with the other unimplemented methods. Here's the latest:

```
! java.lang.UnsupportedOperationException: Method prepareStatement in class org.neo4j.jdbc.Connection is not yet implemented.
! at org.neo4j.jdbc.utils.ExceptionBuilder.buildUnsupportedOperationException(ExceptionBuilder.java:41) ~[neo4j-jdbc-3.0.1-SNAPSHOT.jar:na]
! at org.neo4j.jdbc.Connection.prepareStatement(Connection.java:360) ~[neo4j-jdbc-3.0.1-SNAPSHOT.jar:na]
! at org.sql2o.Query.<init>(Query.java:59) ~[sql2o-1.5.1.jar:na]
! at org.sql2o.Connection.createQuery(Connection.java:83) ~[sql2o-1.5.1.jar:na]
! at org.sql2o.Connection.createQuery(Connection.java:70) ~[sql2o-1.5.1.jar:na]
! at org.sql2o.Connection.createQuery(Connection.java:102) ~[sql2o-1.5.1.jar:na]
```

As for your test, try calling this instead:

```
        try (Connection con = sql2o.beginTransaction()) {
            System.out.println(con.createQuery(sql).executeScalar());
        }
```

I didn't get so far to the labels yet. I wanted to see it blow up with the SQL query strings I'm passing to `con.createQuery(...)`.  My expection/hope was to override our DAO layer to use different Cypher query strings but all the parameters would still work.  Have something like this:

```
interface MovieDao {
  Movie getMovie(String name);
}
abstract class AbstractJdbcMovieDao implements MovieDao {
   abstract String getSelectByNameQuery();
   // implement getMovie() using JDBC and the query string returned from above
}
class SqlMovieDao extends AbstractJdbcMovieDao {
  String getSelectByNameQuery() { return "SELECT ..."; }
}
class NeoMovieDao extends AbstractJdbcMovieDao {
  String getSelectByNameQuery() { return "MATCH ..."; }
}
```

**Comment by jexp** [comment] 2016-07-21 21:04
You could also put the statements in annotations. 

The one by one is unfortunate but we rather wanted to fail than causing unexpected behavior. 

The jdbc interfaces are quite wide ...

Von meinem iPhone gesendet

**Comment by inserpio** [comment] 2016-07-21 22:07
@jaxzin if you were able to provide us a complete use case we would be pleased to take care of it, so to avoid this stop & go approach.

I just updated the jar. Could you please retry with it: https://github.com/neo4j-contrib/neo4j-jdbc/releases/download/3.0.1-SNAPSHOT/neo4j-jdbc-driver-3.0.1-SNAPSHOT.jar

**Comment by inserpio** [comment] 2016-07-26 08:51
Hi @jaxzin, did you find time to check whether SQL2O is working with the last 3.0.1 snapshot? We'd like to close this issue and release the 3.0.1 version on the official repos. Thanks for your precious support!

**Comment by jaxzin** [comment] 2016-07-27 01:02
@inserpio sorry, it got a bit further but ran into an NPE when executing the Cypher query. I need to turn my attention to other things but this was a fun experiment.  I'll likely just change our Dao to use the neo4j apis directly instead of going through a SQL ORM.

**Comment by inserpio** [comment] 2016-07-27 19:34
Ok @jaxzin, thanks for your time and support.
As the JDBC part related to this issue (aka the setTransactionIsolation) is solved and covered by unit tests, I'm closing this issue.
Feel free to open new ones as soon as you'll have some time to spend on this driver and find something that doesn't work.

**Comment by inserpio** [comment] 2016-07-27 19:34
Ok @jaxzin, thanks for your time and support.
As the JDBC part related to this issue (aka the setTransactionIsolation) is solved and covered by unit tests, I'm closing this issue.
Feel free to open new ones as soon as you'll have some time to spend on this driver and find something that doesn't work.

**Closed as completed by inserpio** 2016-07-27 19:34 UTC
Labels: enhancement, http module, bolt module, tools
