### ISSUE TITLE
Queries are broken with HTTP driver

### ISSUE THREAD

**Issue by psilons** [neo4j/neo4j-jdbc#54] opened 2016-06-24 16:24 UTC
code:
Class.forName("org.neo4j.jdbc.Driver");
// switch between these two, proves http is broken for queries
Connection conn = DriverManager.getConnection("jdbc:neo4j:bolt://localhost:7687?noSsl");
 //Connection conn = DriverManager.getConnection("jdbc:neo4j:http://localhost:7474");

String cypher = "MATCH (p:Test) RETURN p"

with bolt connection, query with cypher returns > 1 rows.
with http connection, only 1 row returned.

version is 3.0-RC1. 

It seems that verison 2.3.2 is broken with Neo4j 3.0, but version 2.3.2 works fine with Neo4j 2.2.

Thanks.

**Comment by sim51** [comment] 2016-06-25 15:25
Hi

Can you test with a released version ? (ie not the RC1).

And what do you mean with this sentence, 

`
It seems that verison 2.3.2 is broken with Neo4j 3.0, but version 2.3.2 works fine with Neo4j 2.2.
`

Thanks for your feedback

**Comment by jexp** [comment] 2016-06-25 16:04
@psilons are you sure you're using this version, not the previous one? 

This is a new implementation of a jdbc driver

**Comment by psilons** [comment] 2016-06-25 17:10
In our production environment, we have Neo4j 2.2.7 clusters. We currently use JDBC driver 2.3.2
        <dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j-jdbc</artifactId>
            <version>2.3.2</version>
        </dependency>
Don't have any issue with this.

Now we plan to move to Neo4j 3.0.x, so i play around with Neo4j 3.0.3 and the new JDBC driver 3.0-RC1 in our dev environment.

The new JDBC driver 3.0-RC1 does not work with commons dbcp2 (yet). So I rollback to the above jdbc 2.3.2 driver. But the server is still 3.0.3. With these combination, I got the behavior mentioned in the beginning. I am using http protocol since bolt is not available in 2.3.2.

I understand this is the RC release, may still take some time to get there. But thanks for looking into this. 

Maybe I'll postpone the Neo4j 3.0.x upgrade until JDBC 3.0 driver is fully implemented. I am open for any suggestions.

The reason we use the JDBC driver is that we use Spring JDBC libs.

**Comment by mvitz** [comment] 2016-06-26 07:49
I can confirm the behaviour of the previous (https://github.com/neo4j-contrib/neo4j-jdbc-2x) driver with a Neo4J 3.x Instance.

**Comment by inserpio** [comment] 2016-06-27 08:24
From our side, we can start looking at "_The new JDBC driver 3.0-RC1 does not work with commons dbcp2_".

**Comment by jexp** [comment] 2016-06-28 09:38
@mvitz @psilons there is too much confusing information, can you clearly state what's broken (with a test setup) with the 2.3.2 driver and 3.0.x server and please raise the issue here: https://github.com/neo4j-contrib/neo4j-jdbc-2x

**Comment by mvitz** [comment] 2016-06-28 09:44
Unfortunately I can't find the exact query that was broken in our application. But as I don't expect the 2.3.2 driver to work with a 3.0.x server there is no need for a issue from my side. I'll wait till the 3.x driver is ready to use and migrate after that.

**Comment by albertodeste** [comment] 2016-06-28 10:46
@psilons can you test your spring-jdbc code with the latest neo4j-jdbc release (https://github.com/neo4j-contrib/neo4j-jdbc/releases/download/3.0-RC1/neo4j-jdbc-driver-3.0-RC1.jar) maybe adding it manually to your local maven?
I ask you this because I tested that jar with the movies-java-spring-boot-jdbc example (https://github.com/neo4j-examples/movies-java-spring-boot-jdbc) and it works fine with neo4j 3.0.3 and with 2.3.2, but not with the published version in the m2.neo4j.org repository (probably the one you're using in your project)

**Comment by justinwyer** [comment] 2016-06-28 11:55
I faced the problem using neo4j-jdbc 2.3.2 against neo4j server 3. Updating to neo4j-jdbc 3.0-RC1 resolves the issue. Some queries which return multiple results in the neo4j browser will only return a single result in neo4j-jdbc 2.3.2.

An example of such a query is:
`MATCH (document:Identity:DOCUMENT {id: ?})<-[r:VIEWER|EDITOR|SIGNATORY*1..]-(party:Identity) UNWIND (r) as s RETURN document, COLLECT(DISTINCT type(s)) as permissions, party`

It's worthing noting that other queries work just fine. It's also worth noting I am using spring JDBC Template. I am also using bolt protocol with the 3.0-RC1 driver.

I also experienced another issue using neo4j-jdbc 2.3.2 and neo4j server 3 where multiple result rows were just repeats of the first result row for some queries.

**Comment by glaggia-larus** [comment] 2016-06-28 12:35
@justinwyer it seems to me like a problem on jdbc legacy (2.3.2). Can you please open an issue here?
[https://github.com/neo4j-contrib/neo4j-jdbc-2x](https://github.com/neo4j-contrib/neo4j-jdbc-2x)

**Comment by justinwyer** [comment] 2016-06-28 12:41
@glaggia-larus I was just commenting on the issue as there seemed to be some confusion to the opening poster issue. I also left the comment in case users experience this problem in future.

**Comment by psilons** [comment] 2016-06-28 18:55
@albertodeste Bravo, your version of 3.0RC1 passed my unit tests with Spring JdbcTemplate (I manually downloaded from your link and put it in my local mvn repo). This is great, really appreciate it.
The connection pool works now.

I didn't create an issue in neo4j-jdbc-2x was because I am not sure which way to go, fix it in 2.3.2 or wait for 3.0 release. 

Thanks all for the help.

**Comment by glaggia-larus** [comment] 2016-06-29 07:53
Thanks to you for your feedback,

I'm closing this as solved for this version of the driver (I'm referring to neo4j-jdbc 3.0-RC1 +)

**Closed as completed by glaggia-larus** 2016-06-29 07:53 UTC
Labels: bug
