### ISSUE TITLE
create multi label from jdbc

### ISSUE THREAD

**Issue by zhoumo01** [neo4j/neo4j-jdbc#189] opened 2019-03-06 03:21 UTC
i try to creat multi label entity from neo4j-jdbc, with this clause:
```
create (n:`CourseSource:Module` {color:"#ff4500",content:"[]",lable:"CourseSource",r:30,relationid:426650}) return n
```

but  in neo4j , the entity is not create with multi label， but a label with CourseSource:Module， and i cannot match entity with cypyher:
```
Match (n:CourseSource:Module) return n
Match (n) where n:CourseSource:Module return n
```
they return none because the clause is for multi label match , is there any method to match the entity?

or

the label  has a  ":" should be forbidden cause it's conflict with Cypher match clause

![image](https://user-images.githubusercontent.com/4645808/53853834-08026e00-4002-11e9-8f2a-7a3732e8b001.png)

**Comment by conker84** [comment] 2019-03-06 08:14
Hi @zhoumo01 ,
try with:
```
create (n:`CourseSource`:`Module` {color:"#ff4500",content:"[]",lable:"CourseSource",r:30,relationid:426650}) return n
```

**Comment by conker84** [comment] 2019-03-12 11:09
Hi @zhoumo01 any feedback?

**Comment by conker84** [comment] 2019-03-18 08:45
I'm closing this as it seems not a bug.

**Closed as completed by conker84** 2019-03-18 08:45 UTC
