### ISSUE TITLE
New driver can not reuse connection (java bolt driver)

### ISSUE THREAD

**Issue by rubby33** [neo4j/neo4j-jdbc#69] opened 2016-07-21 03:02 UTC
Hello, I used the old noe4j jdbc drvier based on rest before. it works well for our system except the performance. 
Now, i change it to the neo4j-jdbc-bolt driver.  My system does not work welll.

Sometime it will throw the following error. BTW, i use a pool in our system. 

``` log
org.neo4j.driver.v1.exceptions.ClientException: The current session cannot be reused as the underlying connection with the server has been closed due to unrecoverable errors. Please close this session and retry your statement in another new session.
    at org.neo4j.driver.internal.InternalSession.ensureConnectionIsOpen(InternalSession.java:205)
    at org.neo4j.driver.internal.InternalSession.ensureConnectionIsValidBeforeOpeningTransaction(InternalSession.java:168)
    at org.neo4j.driver.internal.InternalSession.beginTransaction(InternalSession.java:135)
    at org.neo4j.jdbc.bolt.BoltPreparedStatement.executeInternal(BoltPreparedStatement.java:89)
    at org.neo4j.jdbc.bolt.BoltPreparedStatement.executeQuery(BoltPreparedStatement.java:54)
    at com.emotibot.memory.neo4j.JDBCCypherExecutor.executeWithReturn(JDBCCypherExecutor.java:251)
    at com.emotibot.memory.neo4j.JDBCCypherExecutor.getUser(JDBCCypherExecutor.java:2394)
    at com.emotibot.memory.neo4j.query.UsersProfileExecutor.handleQuery(UsersProfileExecutor.java:134)
    at com.emotibot.memory.neo4j.query.UsersProfileExecutor.query(UsersProfileExecutor.java:100)
    at com.emotibot.memory.neo4j.query.AbstractQueryExecutor.execute(AbstractQueryExecutor.java:53)
    at com.emotibot.memory.web.controller.MemoryQueryController.processPost(MemoryQueryController.java:75)
    at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
    at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2454)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
`
```

**Comment by rubby33** [comment] 2016-07-21 03:17
I use a jdbc connection pool . This connection pooling works by re-using connections. Thanks

**Comment by rubby33** [comment] 2016-07-21 10:00
We modify **InternalSession.java**  and it seems that this problem will not happen

``` java
@Override
    public boolean isOpen()
    {
        if(isOpen.get()){
            // make sure connection is open
            return connection.isOpen() ;
        }
        return false;
        // return isOpen.get();
    }
`
```

**Comment by inserpio** [comment] 2016-07-21 15:42
Hi @rubby33, the **InternalSession** class you're mentioning is not part of the JDBC driver, it's part of the java bolt driver we're wrapping instead (https://github.com/neo4j/neo4j-java-driver/blob/1.1/driver/src/main/java/org/neo4j/driver/internal/InternalSession.java).
We cannot change it, but let us investigate a little bit better the problem to find a solution for that issue.

**Comment by inserpio** [comment] 2016-07-26 12:43
Asked for an opinion about this issue to the `java bolt driver` team...

**Comment by inserpio** [comment] 2016-07-26 14:36
Hi @rubby33, we got in touch with the `java driver` team to solve this your issue.
We'd need some more information from you: could you please have a look at [this discussion](https://github.com/neo4j/neo4j-java-driver/issues/205#issuecomment-235283393)?
Thanks for your support.
Lorenzo

**Comment by sim51** [comment] 2016-08-09 11:34
Hi @rubby33 

Have you take a look at the discussion ? 

Can you tell us if you have received some exceptions before you hits this `connection already closed` error?

Thanks by advance.

**Comment by rubby33** [comment] 2016-08-20 07:59
hi，@sim51 sorry for  this later reply.
 I have seen the discussion, zhenlineo has shown how to Kill queries after timeout.  Our system has adopted this approach. It is very useful.

I believe we do not received some exceptions before the "connection already closed error".

Thanks!

**Comment by sim51** [comment] 2016-08-23 16:31
Good news !

So I close this issue. Feel free to re-open it if you received again this exception.

Cheers.

**Closed as completed by sim51** 2016-08-23 16:31 UTC
Labels: enhancement

**Comment by alcarwk** [comment] 2016-08-25 00:26
Hi @sim51, sorry about this but I think I might need this issue reopened.

We have a COTS  product that is using this driver and are having problems similar to those discussed here. Our setup is the standard releases of Neo4j DB 3.0.3  and Neo4j JDBC 3.0. The COTS application is hosted on Linux Tomcat server. We're using BOLT with no TLS security.

The problem we're getting is that connection are not being closed and new connections are being created. Once the number of established connections reaches about 300 things start failing with not being long before the Neo4j DB has Out Of Memory issues. We're still in development so not a lot of queries are being executed at the moment.

As the COTS application managers the connections itself it not possible for use  to apply the fix suggested by **zhenlineo**. 
I have quite a bit of confidence that this COTS products use of JDBC is good. It is using JDBC to integrate with quite a few other databases,  so is likely to be very conservative and standard compliant.

This is the only major problem we have with the Neo4j JDBC Driver and am quite happy with it in most other respects. Thank you all for the hard work on this !!! 

Regards.

PS: I'll see what I can do about getting some diagnostic files. These should confirm if the problem is #69 or something new.
